export {default as BaseServices} from './base.services';
export {IBaseServices} from './base.services';
export {default as DemoServices} from './demo.services';
export {IDemoServices} from './demo.services';
export {default as HouseServices} from './house.services';
export {IHouseServices} from './house.services';
export {default as StoreServices} from './store.services';
export {IStoreServices} from './store.services';
export {default as Test1Services} from './test1.services';
export {ITest1Services} from './test1.services';